# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_webchatmain.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.left = QtWidgets.QFrame(Form)
        self.left.setGeometry(QtCore.QRect(0, 0, 301, 601))
        self.left.setStyleSheet("background:#4D4D4D")
        self.left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left.setObjectName("left")
        self.tabWidget = QtWidgets.QTabWidget(self.left)
        self.tabWidget.setGeometry(QtCore.QRect(0, 60, 301, 541))
        self.tabWidget.setStyleSheet("background:#4D4D4D;color:#FFFFFF")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.currenttab = QtWidgets.QWidget()
        self.currenttab.setObjectName("currenttab")
        self.current = QtWidgets.QListView(self.currenttab)
        self.current.setGeometry(QtCore.QRect(0, 0, 261, 531))
        self.current.setStyleSheet("background:#4D4D4D")
        self.current.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.current.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.current.setIconSize(QtCore.QSize(32, 32))
        self.current.setObjectName("current")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/chat_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("imgs/chat_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.currenttab, icon, "")
        self.friendstab = QtWidgets.QWidget()
        self.friendstab.setObjectName("friendstab")
        self.friends = QtWidgets.QListView(self.friendstab)
        self.friends.setGeometry(QtCore.QRect(0, 50, 251, 481))
        self.friends.setStyleSheet("color:#FFFFFF")
        self.friends.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.friends.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.friends.setIconSize(QtCore.QSize(32, 32))
        self.friends.setObjectName("friends")
        self.searchbar = QtWidgets.QLineEdit(self.friendstab)
        self.searchbar.setGeometry(QtCore.QRect(10, 10, 201, 31))
        self.searchbar.setStyleSheet("background:#AAAAAA")
        self.searchbar.setObjectName("searchbar")
        self.searchButton = QtWidgets.QPushButton(self.friendstab)
        self.searchButton.setGeometry(QtCore.QRect(220, 10, 31, 31))
        self.searchButton.setStyleSheet("background:#AAAAAA")
        self.searchButton.setObjectName("searchButton")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgs/list_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("imgs/list_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.friendstab, icon1, "")
        self.mps = QtWidgets.QWidget()
        self.mps.setObjectName("mps")
        self.mplist = QtWidgets.QListView(self.mps)
        self.mplist.setGeometry(QtCore.QRect(0, 50, 251, 481))
        self.mplist.setStyleSheet("color:#FFFFFF")
        self.mplist.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mplist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mplist.setIconSize(QtCore.QSize(32, 32))
        self.mplist.setObjectName("mplist")
        self.searchmp = QtWidgets.QLineEdit(self.mps)
        self.searchmp.setGeometry(QtCore.QRect(10, 10, 201, 31))
        self.searchmp.setStyleSheet("background:#AAAAAA")
        self.searchmp.setObjectName("searchmp")
        self.searchmpButton = QtWidgets.QPushButton(self.mps)
        self.searchmpButton.setGeometry(QtCore.QRect(220, 10, 31, 31))
        self.searchmpButton.setStyleSheet("background:#AAAAAA")
        self.searchmpButton.setObjectName("searchmpButton")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imgs/mp_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("imgs/mp_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.mps, icon2, "")
        self.translate = QtWidgets.QWidget()
        self.translate.setObjectName("translate")
        self.translateResult = QtWidgets.QLabel(self.translate)
        self.translateResult.setGeometry(QtCore.QRect(10, 150, 231, 131))
        self.translateResult.setAlignment(QtCore.Qt.AlignCenter)
        self.translateResult.setWordWrap(True)
        self.translateResult.setObjectName("translateResult")
        self.translateText = QtWidgets.QLineEdit(self.translate)
        self.translateText.setGeometry(QtCore.QRect(10, 90, 191, 31))
        self.translateText.setStyleSheet("background:#AAAAAA")
        self.translateText.setObjectName("translateText")
        self.translateButton = QtWidgets.QPushButton(self.translate)
        self.translateButton.setGeometry(QtCore.QRect(210, 90, 31, 31))
        self.translateButton.setStyleSheet("background:#AAAAAA")
        self.translateButton.setObjectName("translateButton")
        self.translatesoundButton = QtWidgets.QPushButton(self.translate)
        self.translatesoundButton.setGeometry(QtCore.QRect(80, 300, 80, 25))
        self.translatesoundButton.setObjectName("translatesoundButton")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imgs/translate_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("imgs/translate_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.translate, icon3, "")
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.groupsound = QtWidgets.QCheckBox(self.setting)
        self.groupsound.setGeometry(QtCore.QRect(20, 30, 82, 23))
        self.groupsound.setChecked(True)
        self.groupsound.setTristate(True)
        self.groupsound.setObjectName("groupsound")
        self.friendsound = QtWidgets.QCheckBox(self.setting)
        self.friendsound.setGeometry(QtCore.QRect(20, 60, 81, 23))
        self.friendsound.setChecked(True)
        self.friendsound.setTristate(True)
        self.friendsound.setObjectName("friendsound")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("imgs/setting_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("imgs/setting_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.setting, icon4, "")
        self.move_1 = QtWidgets.QWidget(self.left)
        self.move_1.setGeometry(QtCore.QRect(0, 0, 301, 61))
        self.move_1.setStyleSheet("background:#4D4D4D")
        self.move_1.setObjectName("move_1")
        self.title = QtWidgets.QLabel(self.move_1)
        self.title.setGeometry(QtCore.QRect(80, 10, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title.setFont(font)
        self.title.setStyleSheet("color:#F2F2F2")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.selfpic = QtWidgets.QLabel(self.move_1)
        self.selfpic.setGeometry(QtCore.QRect(10, 10, 41, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selfpic.sizePolicy().hasHeightForWidth())
        self.selfpic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selfpic.setFont(font)
        self.selfpic.setStyleSheet("color:#F2F2F2")
        self.selfpic.setAlignment(QtCore.Qt.AlignCenter)
        self.selfpic.setObjectName("selfpic")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(300, 0, 501, 601))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet("background:#F2F2F2")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.chatname = QtWidgets.QLabel(self.frame_2)
        self.chatname.setGeometry(QtCore.QRect(70, 10, 341, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatname.sizePolicy().hasHeightForWidth())
        self.chatname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chatname.setFont(font)
        self.chatname.setAlignment(QtCore.Qt.AlignCenter)
        self.chatname.setObjectName("chatname")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setGeometry(QtCore.QRect(30, 70, 441, 391))
        self.scrollArea.setStyleSheet("background:#F2F2F2")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 441, 391))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(30, 480, 381, 101))
        self.textEdit.setStyleSheet("background:rgb(255, 255, 255)")
        self.textEdit.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setObjectName("textEdit")
        self.send = QtWidgets.QPushButton(self.frame_2)
        self.send.setGeometry(QtCore.QRect(420, 510, 60, 30))
        self.send.setObjectName("send")
        self.clean = QtWidgets.QPushButton(self.frame_2)
        self.clean.setGeometry(QtCore.QRect(420, 550, 60, 30))
        self.clean.setObjectName("clean")
        self.closeButton = QtWidgets.QPushButton(self.frame_2)
        self.closeButton.setGeometry(QtCore.QRect(460, 0, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.closeButton.setFont(font)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setCheckable(False)
        self.closeButton.setAutoDefault(False)
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")
        self.min = QtWidgets.QPushButton(self.frame_2)
        self.min.setGeometry(QtCore.QRect(420, 0, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.min.setFont(font)
        self.min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min.setCheckable(False)
        self.min.setAutoDefault(False)
        self.min.setFlat(True)
        self.min.setObjectName("min")
        self.mpframe = QtWidgets.QFrame(self.frame_2)
        self.mpframe.setGeometry(QtCore.QRect(30, 70, 441, 391))
        self.mpframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mpframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mpframe.setObjectName("mpframe")
        self.mpb = QtWidgets.QPushButton(self.mpframe)
        self.mpb.setGeometry(QtCore.QRect(420, 0, 21, 21))
        self.mpb.setObjectName("mpb")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.searchButton.setText(_translate("Form", ">>"))
        self.searchmpButton.setText(_translate("Form", ">>"))
        self.translateResult.setText(_translate("Form", "翻译结果"))
        self.translateButton.setText(_translate("Form", ">>"))
        self.translatesoundButton.setText(_translate("Form", "Sound"))
        self.groupsound.setText(_translate("Form", " 群提示音"))
        self.friendsound.setText(_translate("Form", " 好友提示音"))
        self.title.setText(_translate("Form", "Wechat Qt"))
        self.selfpic.setText(_translate("Form", "PIC"))
        self.chatname.setText(_translate("Form", "选择聊天"))
        self.send.setText(_translate("Form", "发送"))
        self.clean.setText(_translate("Form", "清除"))
        self.closeButton.setText(_translate("Form", "×"))
        self.min.setText(_translate("Form", "－"))
        self.mpb.setText(_translate("Form", "刷"))
